// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _KernelMaker_HH_
#define _KernelMaker_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "real379.h"
#include "imag380.h"
#include "WienerDeblur_fptreOg.h"
#include "WienerDeblur_sitofYi.h"
#include "WienerDeblur_dexpg8j.h"
#include "WienerDeblur_mac_hbi.h"

namespace ap_rtl {

struct KernelMaker : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > kernel_M_real_din;
    sc_in< sc_logic > kernel_M_real_full_n;
    sc_out< sc_logic > kernel_M_real_write;
    sc_out< sc_lv<32> > kernel_M_imag_din;
    sc_in< sc_logic > kernel_M_imag_full_n;
    sc_out< sc_logic > kernel_M_imag_write;
    sc_signal< sc_logic > ap_var_for_const1;
    sc_signal< sc_lv<32> > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const2;


    // Module declarations
    KernelMaker(sc_module_name name);
    SC_HAS_PROCESS(KernelMaker);

    ~KernelMaker();

    sc_trace_file* mVcdFile;

    real379* StgValue_88_real379_fu_68;
    imag380* StgValue_89_imag380_fu_75;
    WienerDeblur_fptreOg<1,1,64,32>* WienerDeblur_fptreOg_U32;
    WienerDeblur_sitofYi<1,6,32,64>* WienerDeblur_sitofYi_U33;
    WienerDeblur_dexpg8j<1,18,64,64,64>* WienerDeblur_dexpg8j_U34;
    WienerDeblur_mac_hbi<1,1,9,9,17,17>* WienerDeblur_mac_hbi_U35;
    sc_signal< sc_lv<29> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > StgValue_88_real379_fu_68_complex_float_M_real_blk_n;
    sc_signal< sc_logic > kernel_M_real_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state29;
    sc_signal< sc_logic > StgValue_89_imag380_fu_75_complex_float_M_imag_blk_n;
    sc_signal< sc_logic > kernel_M_imag_blk_n;
    sc_signal< sc_lv<9> > i_3_fu_101_p2;
    sc_signal< sc_lv<9> > i_3_reg_220;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<17> > tmp_138_cast_fu_117_p2;
    sc_signal< sc_lv<17> > tmp_138_cast_reg_225;
    sc_signal< sc_lv<1> > exitcond_fu_95_p2;
    sc_signal< sc_lv<9> > j_1_fu_129_p2;
    sc_signal< sc_lv<9> > j_1_reg_233;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<17> > grp_fu_208_p3;
    sc_signal< sc_lv<17> > tmp_93_reg_238;
    sc_signal< sc_lv<1> > exitcond1_fu_123_p2;
    sc_signal< sc_lv<1> > tmp_113_reg_243;
    sc_signal< sc_lv<2> > tmp_97_reg_248;
    sc_signal< sc_lv<4> > tmp_99_fu_197_p3;
    sc_signal< sc_lv<4> > tmp_99_reg_253;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > grp_fu_87_p1;
    sc_signal< sc_lv<64> > tmp_100_reg_263;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<64> > grp_fu_90_p2;
    sc_signal< sc_lv<64> > tmp_101_reg_268;
    sc_signal< sc_logic > ap_CS_fsm_state28;
    sc_signal< sc_logic > StgValue_88_real379_fu_68_ap_start;
    sc_signal< sc_logic > StgValue_88_real379_fu_68_ap_done;
    sc_signal< sc_logic > StgValue_88_real379_fu_68_ap_idle;
    sc_signal< sc_logic > StgValue_88_real379_fu_68_ap_ready;
    sc_signal< sc_lv<32> > StgValue_88_real379_fu_68_complex_float_M_real_din;
    sc_signal< sc_logic > StgValue_88_real379_fu_68_complex_float_M_real_write;
    sc_signal< sc_logic > StgValue_89_imag380_fu_75_ap_start;
    sc_signal< sc_logic > StgValue_89_imag380_fu_75_ap_done;
    sc_signal< sc_logic > StgValue_89_imag380_fu_75_ap_idle;
    sc_signal< sc_logic > StgValue_89_imag380_fu_75_ap_ready;
    sc_signal< sc_lv<32> > StgValue_89_imag380_fu_75_complex_float_M_imag_din;
    sc_signal< sc_logic > StgValue_89_imag380_fu_75_complex_float_M_imag_write;
    sc_signal< sc_lv<9> > i_reg_46;
    sc_signal< sc_lv<9> > j_reg_57;
    sc_signal< bool > ap_block_state29;
    sc_signal< sc_lv<32> > tmp_102_fu_83_p1;
    sc_signal< sc_lv<32> > grp_fu_87_p0;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<9> > tmp_s_fu_107_p2;
    sc_signal< sc_lv<9> > tmp_138_cast_fu_117_p0;
    sc_signal< sc_lv<17> > tmp_fu_113_p1;
    sc_signal< sc_lv<9> > tmp_138_cast_fu_117_p1;
    sc_signal< sc_lv<9> > tmp_92_fu_135_p2;
    sc_signal< sc_lv<17> > p_neg_fu_161_p2;
    sc_signal< sc_lv<2> > tmp_95_fu_166_p4;
    sc_signal< sc_lv<3> > tmp_96_fu_176_p1;
    sc_signal< sc_lv<3> > tmp_98_fu_184_p1;
    sc_signal< sc_lv<4> > p_lshr_f_cast_fu_187_p1;
    sc_signal< sc_lv<4> > p_lshr_cast_fu_180_p1;
    sc_signal< sc_lv<4> > p_neg_f_fu_191_p2;
    sc_signal< sc_lv<9> > grp_fu_208_p0;
    sc_signal< sc_lv<17> > tmp_91_fu_141_p1;
    sc_signal< sc_lv<9> > grp_fu_208_p1;
    sc_signal< sc_lv<29> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<29> ap_ST_fsm_state1;
    static const sc_lv<29> ap_ST_fsm_state2;
    static const sc_lv<29> ap_ST_fsm_state3;
    static const sc_lv<29> ap_ST_fsm_state4;
    static const sc_lv<29> ap_ST_fsm_state5;
    static const sc_lv<29> ap_ST_fsm_state6;
    static const sc_lv<29> ap_ST_fsm_state7;
    static const sc_lv<29> ap_ST_fsm_state8;
    static const sc_lv<29> ap_ST_fsm_state9;
    static const sc_lv<29> ap_ST_fsm_state10;
    static const sc_lv<29> ap_ST_fsm_state11;
    static const sc_lv<29> ap_ST_fsm_state12;
    static const sc_lv<29> ap_ST_fsm_state13;
    static const sc_lv<29> ap_ST_fsm_state14;
    static const sc_lv<29> ap_ST_fsm_state15;
    static const sc_lv<29> ap_ST_fsm_state16;
    static const sc_lv<29> ap_ST_fsm_state17;
    static const sc_lv<29> ap_ST_fsm_state18;
    static const sc_lv<29> ap_ST_fsm_state19;
    static const sc_lv<29> ap_ST_fsm_state20;
    static const sc_lv<29> ap_ST_fsm_state21;
    static const sc_lv<29> ap_ST_fsm_state22;
    static const sc_lv<29> ap_ST_fsm_state23;
    static const sc_lv<29> ap_ST_fsm_state24;
    static const sc_lv<29> ap_ST_fsm_state25;
    static const sc_lv<29> ap_ST_fsm_state26;
    static const sc_lv<29> ap_ST_fsm_state27;
    static const sc_lv<29> ap_ST_fsm_state28;
    static const sc_lv<29> ap_ST_fsm_state29;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<9> ap_const_lv9_100;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<9> ap_const_lv9_180;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<17> ap_const_lv17_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_StgValue_88_real379_fu_68_ap_start();
    void thread_StgValue_89_imag380_fu_75_ap_start();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state28();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_state29();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond1_fu_123_p2();
    void thread_exitcond_fu_95_p2();
    void thread_grp_fu_208_p0();
    void thread_grp_fu_208_p1();
    void thread_grp_fu_87_p0();
    void thread_i_3_fu_101_p2();
    void thread_j_1_fu_129_p2();
    void thread_kernel_M_imag_blk_n();
    void thread_kernel_M_imag_din();
    void thread_kernel_M_imag_write();
    void thread_kernel_M_real_blk_n();
    void thread_kernel_M_real_din();
    void thread_kernel_M_real_write();
    void thread_p_lshr_cast_fu_180_p1();
    void thread_p_lshr_f_cast_fu_187_p1();
    void thread_p_neg_f_fu_191_p2();
    void thread_p_neg_fu_161_p2();
    void thread_tmp_138_cast_fu_117_p0();
    void thread_tmp_138_cast_fu_117_p1();
    void thread_tmp_138_cast_fu_117_p2();
    void thread_tmp_91_fu_141_p1();
    void thread_tmp_92_fu_135_p2();
    void thread_tmp_95_fu_166_p4();
    void thread_tmp_96_fu_176_p1();
    void thread_tmp_98_fu_184_p1();
    void thread_tmp_99_fu_197_p3();
    void thread_tmp_fu_113_p1();
    void thread_tmp_s_fu_107_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
