// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrix_modulus_HH_
#define _matrix_modulus_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "pow_generic_double_s.h"
#include "real_r.h"
#include "imag.h"
#include "WienerDeblur_fptreOg.h"
#include "WienerDeblur_fpexKfY.h"
#include "WienerDeblur_daddLf8.h"
#include "WienerDeblur_dsqrMgi.h"

namespace ap_rtl {

struct matrix_modulus : public sc_module {
    // Port declarations 18
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > fft_kernel_M_real_dout;
    sc_in< sc_logic > fft_kernel_M_real_empty_n;
    sc_out< sc_logic > fft_kernel_M_real_read;
    sc_in< sc_lv<32> > fft_kernel_M_imag_dout;
    sc_in< sc_logic > fft_kernel_M_imag_empty_n;
    sc_out< sc_logic > fft_kernel_M_imag_read;
    sc_out< sc_lv<32> > fft_kernel_modu_M_r_din;
    sc_in< sc_logic > fft_kernel_modu_M_r_full_n;
    sc_out< sc_logic > fft_kernel_modu_M_r_write;
    sc_out< sc_lv<32> > fft_kernel_modu_M_i_din;
    sc_in< sc_logic > fft_kernel_modu_M_i_full_n;
    sc_out< sc_logic > fft_kernel_modu_M_i_write;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;


    // Module declarations
    matrix_modulus(sc_module_name name);
    SC_HAS_PROCESS(matrix_modulus);

    ~matrix_modulus();

    sc_trace_file* mVcdFile;

    pow_generic_double_s* grp_pow_generic_double_s_fu_96;
    pow_generic_double_s* grp_pow_generic_double_s_fu_125;
    real_r* StgValue_299_real_r_fu_154;
    imag* StgValue_300_imag_fu_161;
    WienerDeblur_fptreOg<1,1,64,32>* WienerDeblur_fptreOg_U108;
    WienerDeblur_fpexKfY<1,1,32,64>* WienerDeblur_fpexKfY_U109;
    WienerDeblur_fpexKfY<1,1,32,64>* WienerDeblur_fpexKfY_U110;
    WienerDeblur_daddLf8<1,5,64,64,64>* WienerDeblur_daddLf8_U111;
    WienerDeblur_dsqrMgi<1,31,64,64,64>* WienerDeblur_dsqrMgi_U112;
    sc_signal< sc_lv<108> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > fft_kernel_M_real_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond_fu_198_p2;
    sc_signal< sc_logic > fft_kernel_M_imag_blk_n;
    sc_signal< sc_logic > StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n;
    sc_signal< sc_logic > fft_kernel_modu_M_r_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state108;
    sc_signal< sc_logic > StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n;
    sc_signal< sc_logic > fft_kernel_modu_M_i_blk_n;
    sc_signal< sc_lv<9> > r_2_fu_192_p2;
    sc_signal< sc_lv<9> > r_2_reg_213;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<9> > c_2_fu_204_p2;
    sc_signal< sc_lv<9> > c_2_reg_221;
    sc_signal< bool > ap_block_state3;
    sc_signal< sc_lv<32> > fft_kernel_M_real_r_reg_226;
    sc_signal< sc_lv<32> > fft_kernel_M_imag_r_reg_231;
    sc_signal< sc_lv<64> > x_assign_fu_171_p1;
    sc_signal< sc_lv<64> > x_assign_reg_236;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<64> > x_assign_1_fu_174_p1;
    sc_signal< sc_lv<64> > x_assign_1_reg_241;
    sc_signal< sc_lv<64> > grp_pow_generic_double_s_fu_96_ap_return;
    sc_signal< sc_lv<64> > tmp_i_reg_246;
    sc_signal< sc_logic > ap_CS_fsm_state71;
    sc_signal< sc_lv<64> > grp_pow_generic_double_s_fu_125_ap_return;
    sc_signal< sc_lv<64> > tmp_i1_reg_251;
    sc_signal< sc_lv<64> > grp_fu_177_p2;
    sc_signal< sc_lv<64> > tmp_s_reg_256;
    sc_signal< sc_logic > ap_CS_fsm_state76;
    sc_signal< sc_lv<64> > grp_fu_181_p2;
    sc_signal< sc_lv<64> > tmp_39_reg_261;
    sc_signal< sc_logic > ap_CS_fsm_state107;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_96_ap_start;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_96_ap_done;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_96_ap_idle;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_96_ap_ready;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_125_ap_start;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_125_ap_done;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_125_ap_idle;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_125_ap_ready;
    sc_signal< sc_logic > StgValue_299_real_r_fu_154_ap_start;
    sc_signal< sc_logic > StgValue_299_real_r_fu_154_ap_done;
    sc_signal< sc_logic > StgValue_299_real_r_fu_154_ap_idle;
    sc_signal< sc_logic > StgValue_299_real_r_fu_154_ap_ready;
    sc_signal< sc_lv<32> > StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_din;
    sc_signal< sc_logic > StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_write;
    sc_signal< sc_logic > StgValue_300_imag_fu_161_ap_start;
    sc_signal< sc_logic > StgValue_300_imag_fu_161_ap_done;
    sc_signal< sc_logic > StgValue_300_imag_fu_161_ap_idle;
    sc_signal< sc_logic > StgValue_300_imag_fu_161_ap_ready;
    sc_signal< sc_lv<32> > StgValue_300_imag_fu_161_fft_kernel_modu_M_i_din;
    sc_signal< sc_logic > StgValue_300_imag_fu_161_fft_kernel_modu_M_i_write;
    sc_signal< sc_lv<9> > r_reg_74;
    sc_signal< sc_lv<9> > c_reg_85;
    sc_signal< bool > ap_block_state108;
    sc_signal< sc_lv<1> > exitcond1_fu_186_p2;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_96_ap_start_reg;
    sc_signal< sc_lv<108> > ap_NS_fsm;
    sc_signal< sc_logic > ap_NS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > grp_pow_generic_double_s_fu_125_ap_start_reg;
    sc_signal< sc_lv<32> > tmp_40_fu_167_p1;
    sc_signal< sc_logic > ap_CS_fsm_state72;
    sc_signal< sc_logic > ap_CS_fsm_state77;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<108> ap_ST_fsm_state1;
    static const sc_lv<108> ap_ST_fsm_state2;
    static const sc_lv<108> ap_ST_fsm_state3;
    static const sc_lv<108> ap_ST_fsm_state4;
    static const sc_lv<108> ap_ST_fsm_state5;
    static const sc_lv<108> ap_ST_fsm_state6;
    static const sc_lv<108> ap_ST_fsm_state7;
    static const sc_lv<108> ap_ST_fsm_state8;
    static const sc_lv<108> ap_ST_fsm_state9;
    static const sc_lv<108> ap_ST_fsm_state10;
    static const sc_lv<108> ap_ST_fsm_state11;
    static const sc_lv<108> ap_ST_fsm_state12;
    static const sc_lv<108> ap_ST_fsm_state13;
    static const sc_lv<108> ap_ST_fsm_state14;
    static const sc_lv<108> ap_ST_fsm_state15;
    static const sc_lv<108> ap_ST_fsm_state16;
    static const sc_lv<108> ap_ST_fsm_state17;
    static const sc_lv<108> ap_ST_fsm_state18;
    static const sc_lv<108> ap_ST_fsm_state19;
    static const sc_lv<108> ap_ST_fsm_state20;
    static const sc_lv<108> ap_ST_fsm_state21;
    static const sc_lv<108> ap_ST_fsm_state22;
    static const sc_lv<108> ap_ST_fsm_state23;
    static const sc_lv<108> ap_ST_fsm_state24;
    static const sc_lv<108> ap_ST_fsm_state25;
    static const sc_lv<108> ap_ST_fsm_state26;
    static const sc_lv<108> ap_ST_fsm_state27;
    static const sc_lv<108> ap_ST_fsm_state28;
    static const sc_lv<108> ap_ST_fsm_state29;
    static const sc_lv<108> ap_ST_fsm_state30;
    static const sc_lv<108> ap_ST_fsm_state31;
    static const sc_lv<108> ap_ST_fsm_state32;
    static const sc_lv<108> ap_ST_fsm_state33;
    static const sc_lv<108> ap_ST_fsm_state34;
    static const sc_lv<108> ap_ST_fsm_state35;
    static const sc_lv<108> ap_ST_fsm_state36;
    static const sc_lv<108> ap_ST_fsm_state37;
    static const sc_lv<108> ap_ST_fsm_state38;
    static const sc_lv<108> ap_ST_fsm_state39;
    static const sc_lv<108> ap_ST_fsm_state40;
    static const sc_lv<108> ap_ST_fsm_state41;
    static const sc_lv<108> ap_ST_fsm_state42;
    static const sc_lv<108> ap_ST_fsm_state43;
    static const sc_lv<108> ap_ST_fsm_state44;
    static const sc_lv<108> ap_ST_fsm_state45;
    static const sc_lv<108> ap_ST_fsm_state46;
    static const sc_lv<108> ap_ST_fsm_state47;
    static const sc_lv<108> ap_ST_fsm_state48;
    static const sc_lv<108> ap_ST_fsm_state49;
    static const sc_lv<108> ap_ST_fsm_state50;
    static const sc_lv<108> ap_ST_fsm_state51;
    static const sc_lv<108> ap_ST_fsm_state52;
    static const sc_lv<108> ap_ST_fsm_state53;
    static const sc_lv<108> ap_ST_fsm_state54;
    static const sc_lv<108> ap_ST_fsm_state55;
    static const sc_lv<108> ap_ST_fsm_state56;
    static const sc_lv<108> ap_ST_fsm_state57;
    static const sc_lv<108> ap_ST_fsm_state58;
    static const sc_lv<108> ap_ST_fsm_state59;
    static const sc_lv<108> ap_ST_fsm_state60;
    static const sc_lv<108> ap_ST_fsm_state61;
    static const sc_lv<108> ap_ST_fsm_state62;
    static const sc_lv<108> ap_ST_fsm_state63;
    static const sc_lv<108> ap_ST_fsm_state64;
    static const sc_lv<108> ap_ST_fsm_state65;
    static const sc_lv<108> ap_ST_fsm_state66;
    static const sc_lv<108> ap_ST_fsm_state67;
    static const sc_lv<108> ap_ST_fsm_state68;
    static const sc_lv<108> ap_ST_fsm_state69;
    static const sc_lv<108> ap_ST_fsm_state70;
    static const sc_lv<108> ap_ST_fsm_state71;
    static const sc_lv<108> ap_ST_fsm_state72;
    static const sc_lv<108> ap_ST_fsm_state73;
    static const sc_lv<108> ap_ST_fsm_state74;
    static const sc_lv<108> ap_ST_fsm_state75;
    static const sc_lv<108> ap_ST_fsm_state76;
    static const sc_lv<108> ap_ST_fsm_state77;
    static const sc_lv<108> ap_ST_fsm_state78;
    static const sc_lv<108> ap_ST_fsm_state79;
    static const sc_lv<108> ap_ST_fsm_state80;
    static const sc_lv<108> ap_ST_fsm_state81;
    static const sc_lv<108> ap_ST_fsm_state82;
    static const sc_lv<108> ap_ST_fsm_state83;
    static const sc_lv<108> ap_ST_fsm_state84;
    static const sc_lv<108> ap_ST_fsm_state85;
    static const sc_lv<108> ap_ST_fsm_state86;
    static const sc_lv<108> ap_ST_fsm_state87;
    static const sc_lv<108> ap_ST_fsm_state88;
    static const sc_lv<108> ap_ST_fsm_state89;
    static const sc_lv<108> ap_ST_fsm_state90;
    static const sc_lv<108> ap_ST_fsm_state91;
    static const sc_lv<108> ap_ST_fsm_state92;
    static const sc_lv<108> ap_ST_fsm_state93;
    static const sc_lv<108> ap_ST_fsm_state94;
    static const sc_lv<108> ap_ST_fsm_state95;
    static const sc_lv<108> ap_ST_fsm_state96;
    static const sc_lv<108> ap_ST_fsm_state97;
    static const sc_lv<108> ap_ST_fsm_state98;
    static const sc_lv<108> ap_ST_fsm_state99;
    static const sc_lv<108> ap_ST_fsm_state100;
    static const sc_lv<108> ap_ST_fsm_state101;
    static const sc_lv<108> ap_ST_fsm_state102;
    static const sc_lv<108> ap_ST_fsm_state103;
    static const sc_lv<108> ap_ST_fsm_state104;
    static const sc_lv<108> ap_ST_fsm_state105;
    static const sc_lv<108> ap_ST_fsm_state106;
    static const sc_lv<108> ap_ST_fsm_state107;
    static const sc_lv<108> ap_ST_fsm_state108;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_6B;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_46;
    static const sc_lv<32> ap_const_lv32_4B;
    static const sc_lv<32> ap_const_lv32_6A;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_47;
    static const sc_lv<32> ap_const_lv32_4C;
    static const sc_lv<9> ap_const_lv9_100;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_StgValue_299_real_r_fu_154_ap_start();
    void thread_StgValue_300_imag_fu_161_ap_start();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state107();
    void thread_ap_CS_fsm_state108();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state71();
    void thread_ap_CS_fsm_state72();
    void thread_ap_CS_fsm_state76();
    void thread_ap_CS_fsm_state77();
    void thread_ap_NS_fsm_state5();
    void thread_ap_block_state108();
    void thread_ap_block_state3();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_c_2_fu_204_p2();
    void thread_exitcond1_fu_186_p2();
    void thread_exitcond_fu_198_p2();
    void thread_fft_kernel_M_imag_blk_n();
    void thread_fft_kernel_M_imag_read();
    void thread_fft_kernel_M_real_blk_n();
    void thread_fft_kernel_M_real_read();
    void thread_fft_kernel_modu_M_i_blk_n();
    void thread_fft_kernel_modu_M_i_din();
    void thread_fft_kernel_modu_M_i_write();
    void thread_fft_kernel_modu_M_r_blk_n();
    void thread_fft_kernel_modu_M_r_din();
    void thread_fft_kernel_modu_M_r_write();
    void thread_grp_pow_generic_double_s_fu_125_ap_start();
    void thread_grp_pow_generic_double_s_fu_96_ap_start();
    void thread_r_2_fu_192_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
