// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_modulus.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_modulus::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_modulus::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<108> matrix_modulus::ap_ST_fsm_state1 = "1";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state2 = "10";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state3 = "100";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state4 = "1000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state5 = "10000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state6 = "100000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state7 = "1000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state8 = "10000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state9 = "100000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state10 = "1000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state11 = "10000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state12 = "100000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state61 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state62 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state63 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state64 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state65 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state66 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state67 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state68 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state69 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state70 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state71 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state72 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state73 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state74 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state75 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state76 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state77 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state78 = "100000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state79 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state80 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state81 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state82 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state83 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state84 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state85 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state86 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state87 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state88 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state89 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state90 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state91 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state92 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state93 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state94 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state95 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state96 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state97 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state98 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state99 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state100 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state101 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state102 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state103 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state104 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state105 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state106 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state107 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<108> matrix_modulus::ap_ST_fsm_state108 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> matrix_modulus::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrix_modulus::ap_const_lv32_2 = "10";
const sc_lv<1> matrix_modulus::ap_const_lv1_0 = "0";
const sc_lv<32> matrix_modulus::ap_const_lv32_6B = "1101011";
const sc_lv<32> matrix_modulus::ap_const_lv32_1 = "1";
const sc_lv<32> matrix_modulus::ap_const_lv32_3 = "11";
const sc_lv<32> matrix_modulus::ap_const_lv32_46 = "1000110";
const sc_lv<32> matrix_modulus::ap_const_lv32_4B = "1001011";
const sc_lv<32> matrix_modulus::ap_const_lv32_6A = "1101010";
const sc_lv<9> matrix_modulus::ap_const_lv9_0 = "000000000";
const sc_lv<1> matrix_modulus::ap_const_lv1_1 = "1";
const sc_lv<32> matrix_modulus::ap_const_lv32_4 = "100";
const sc_lv<32> matrix_modulus::ap_const_lv32_47 = "1000111";
const sc_lv<32> matrix_modulus::ap_const_lv32_4C = "1001100";
const sc_lv<9> matrix_modulus::ap_const_lv9_100 = "100000000";
const sc_lv<9> matrix_modulus::ap_const_lv9_1 = "1";
const sc_lv<64> matrix_modulus::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const bool matrix_modulus::ap_const_boolean_1 = true;

matrix_modulus::matrix_modulus(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_pow_generic_double_s_fu_96 = new pow_generic_double_s("grp_pow_generic_double_s_fu_96");
    grp_pow_generic_double_s_fu_96->ap_clk(ap_clk);
    grp_pow_generic_double_s_fu_96->ap_rst(ap_rst);
    grp_pow_generic_double_s_fu_96->ap_start(grp_pow_generic_double_s_fu_96_ap_start);
    grp_pow_generic_double_s_fu_96->ap_done(grp_pow_generic_double_s_fu_96_ap_done);
    grp_pow_generic_double_s_fu_96->ap_idle(grp_pow_generic_double_s_fu_96_ap_idle);
    grp_pow_generic_double_s_fu_96->ap_ready(grp_pow_generic_double_s_fu_96_ap_ready);
    grp_pow_generic_double_s_fu_96->base_r(x_assign_reg_236);
    grp_pow_generic_double_s_fu_96->ap_return(grp_pow_generic_double_s_fu_96_ap_return);
    grp_pow_generic_double_s_fu_125 = new pow_generic_double_s("grp_pow_generic_double_s_fu_125");
    grp_pow_generic_double_s_fu_125->ap_clk(ap_clk);
    grp_pow_generic_double_s_fu_125->ap_rst(ap_rst);
    grp_pow_generic_double_s_fu_125->ap_start(grp_pow_generic_double_s_fu_125_ap_start);
    grp_pow_generic_double_s_fu_125->ap_done(grp_pow_generic_double_s_fu_125_ap_done);
    grp_pow_generic_double_s_fu_125->ap_idle(grp_pow_generic_double_s_fu_125_ap_idle);
    grp_pow_generic_double_s_fu_125->ap_ready(grp_pow_generic_double_s_fu_125_ap_ready);
    grp_pow_generic_double_s_fu_125->base_r(x_assign_1_reg_241);
    grp_pow_generic_double_s_fu_125->ap_return(grp_pow_generic_double_s_fu_125_ap_return);
    StgValue_299_real_r_fu_154 = new real_r("StgValue_299_real_r_fu_154");
    StgValue_299_real_r_fu_154->ap_clk(ap_clk);
    StgValue_299_real_r_fu_154->ap_rst(ap_rst);
    StgValue_299_real_r_fu_154->ap_start(StgValue_299_real_r_fu_154_ap_start);
    StgValue_299_real_r_fu_154->ap_done(StgValue_299_real_r_fu_154_ap_done);
    StgValue_299_real_r_fu_154->ap_idle(StgValue_299_real_r_fu_154_ap_idle);
    StgValue_299_real_r_fu_154->ap_ready(StgValue_299_real_r_fu_154_ap_ready);
    StgValue_299_real_r_fu_154->p_val(tmp_40_fu_167_p1);
    StgValue_299_real_r_fu_154->fft_kernel_modu_M_r_din(StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_din);
    StgValue_299_real_r_fu_154->fft_kernel_modu_M_r_full_n(fft_kernel_modu_M_r_full_n);
    StgValue_299_real_r_fu_154->fft_kernel_modu_M_r_write(StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_write);
    StgValue_299_real_r_fu_154->fft_kernel_modu_M_r_blk_n(StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n);
    StgValue_300_imag_fu_161 = new imag("StgValue_300_imag_fu_161");
    StgValue_300_imag_fu_161->ap_clk(ap_clk);
    StgValue_300_imag_fu_161->ap_rst(ap_rst);
    StgValue_300_imag_fu_161->ap_start(StgValue_300_imag_fu_161_ap_start);
    StgValue_300_imag_fu_161->ap_done(StgValue_300_imag_fu_161_ap_done);
    StgValue_300_imag_fu_161->ap_idle(StgValue_300_imag_fu_161_ap_idle);
    StgValue_300_imag_fu_161->ap_ready(StgValue_300_imag_fu_161_ap_ready);
    StgValue_300_imag_fu_161->fft_kernel_modu_M_i_din(StgValue_300_imag_fu_161_fft_kernel_modu_M_i_din);
    StgValue_300_imag_fu_161->fft_kernel_modu_M_i_full_n(fft_kernel_modu_M_i_full_n);
    StgValue_300_imag_fu_161->fft_kernel_modu_M_i_write(StgValue_300_imag_fu_161_fft_kernel_modu_M_i_write);
    StgValue_300_imag_fu_161->fft_kernel_modu_M_i_blk_n(StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n);
    WienerDeblur_fptreOg_U108 = new WienerDeblur_fptreOg<1,1,64,32>("WienerDeblur_fptreOg_U108");
    WienerDeblur_fptreOg_U108->din0(tmp_39_reg_261);
    WienerDeblur_fptreOg_U108->dout(tmp_40_fu_167_p1);
    WienerDeblur_fpexKfY_U109 = new WienerDeblur_fpexKfY<1,1,32,64>("WienerDeblur_fpexKfY_U109");
    WienerDeblur_fpexKfY_U109->din0(fft_kernel_M_real_r_reg_226);
    WienerDeblur_fpexKfY_U109->dout(x_assign_fu_171_p1);
    WienerDeblur_fpexKfY_U110 = new WienerDeblur_fpexKfY<1,1,32,64>("WienerDeblur_fpexKfY_U110");
    WienerDeblur_fpexKfY_U110->din0(fft_kernel_M_imag_r_reg_231);
    WienerDeblur_fpexKfY_U110->dout(x_assign_1_fu_174_p1);
    WienerDeblur_daddLf8_U111 = new WienerDeblur_daddLf8<1,5,64,64,64>("WienerDeblur_daddLf8_U111");
    WienerDeblur_daddLf8_U111->clk(ap_clk);
    WienerDeblur_daddLf8_U111->reset(ap_rst);
    WienerDeblur_daddLf8_U111->din0(tmp_i_reg_246);
    WienerDeblur_daddLf8_U111->din1(tmp_i1_reg_251);
    WienerDeblur_daddLf8_U111->ce(ap_var_for_const0);
    WienerDeblur_daddLf8_U111->dout(grp_fu_177_p2);
    WienerDeblur_dsqrMgi_U112 = new WienerDeblur_dsqrMgi<1,31,64,64,64>("WienerDeblur_dsqrMgi_U112");
    WienerDeblur_dsqrMgi_U112->clk(ap_clk);
    WienerDeblur_dsqrMgi_U112->reset(ap_rst);
    WienerDeblur_dsqrMgi_U112->din0(ap_var_for_const1);
    WienerDeblur_dsqrMgi_U112->din1(tmp_s_reg_256);
    WienerDeblur_dsqrMgi_U112->ce(ap_var_for_const0);
    WienerDeblur_dsqrMgi_U112->dout(grp_fu_181_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_StgValue_299_real_r_fu_154_ap_start);
    sensitive << ( ap_CS_fsm_state108 );
    sensitive << ( StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n );

    SC_METHOD(thread_StgValue_300_imag_fu_161_ap_start);
    sensitive << ( StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n );
    sensitive << ( ap_CS_fsm_state108 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state107);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state108);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state71);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state72);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state76);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state77);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_NS_fsm_state5);
    sensitive << ( ap_NS_fsm );

    SC_METHOD(thread_ap_block_state108);
    sensitive << ( StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n );
    sensitive << ( StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( fft_kernel_M_real_empty_n );
    sensitive << ( fft_kernel_M_imag_empty_n );
    sensitive << ( exitcond_fu_198_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_186_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_186_p2 );

    SC_METHOD(thread_c_2_fu_204_p2);
    sensitive << ( c_reg_85 );

    SC_METHOD(thread_exitcond1_fu_186_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_reg_74 );

    SC_METHOD(thread_exitcond_fu_198_p2);
    sensitive << ( fft_kernel_M_real_empty_n );
    sensitive << ( fft_kernel_M_imag_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_198_p2 );
    sensitive << ( c_reg_85 );

    SC_METHOD(thread_fft_kernel_M_imag_blk_n);
    sensitive << ( fft_kernel_M_imag_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_198_p2 );

    SC_METHOD(thread_fft_kernel_M_imag_read);
    sensitive << ( fft_kernel_M_real_empty_n );
    sensitive << ( fft_kernel_M_imag_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_198_p2 );

    SC_METHOD(thread_fft_kernel_M_real_blk_n);
    sensitive << ( fft_kernel_M_real_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_198_p2 );

    SC_METHOD(thread_fft_kernel_M_real_read);
    sensitive << ( fft_kernel_M_real_empty_n );
    sensitive << ( fft_kernel_M_imag_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_198_p2 );

    SC_METHOD(thread_fft_kernel_modu_M_i_blk_n);
    sensitive << ( ap_CS_fsm_state108 );
    sensitive << ( StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n );

    SC_METHOD(thread_fft_kernel_modu_M_i_din);
    sensitive << ( ap_CS_fsm_state108 );
    sensitive << ( StgValue_300_imag_fu_161_fft_kernel_modu_M_i_din );

    SC_METHOD(thread_fft_kernel_modu_M_i_write);
    sensitive << ( ap_CS_fsm_state108 );
    sensitive << ( StgValue_300_imag_fu_161_fft_kernel_modu_M_i_write );

    SC_METHOD(thread_fft_kernel_modu_M_r_blk_n);
    sensitive << ( StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n );
    sensitive << ( ap_CS_fsm_state108 );

    SC_METHOD(thread_fft_kernel_modu_M_r_din);
    sensitive << ( ap_CS_fsm_state108 );
    sensitive << ( StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_din );

    SC_METHOD(thread_fft_kernel_modu_M_r_write);
    sensitive << ( ap_CS_fsm_state108 );
    sensitive << ( StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_write );

    SC_METHOD(thread_grp_pow_generic_double_s_fu_125_ap_start);
    sensitive << ( grp_pow_generic_double_s_fu_125_ap_start_reg );

    SC_METHOD(thread_grp_pow_generic_double_s_fu_96_ap_start);
    sensitive << ( grp_pow_generic_double_s_fu_96_ap_start_reg );

    SC_METHOD(thread_r_2_fu_192_p2);
    sensitive << ( r_reg_74 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( fft_kernel_M_real_empty_n );
    sensitive << ( fft_kernel_M_imag_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_198_p2 );
    sensitive << ( StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n );
    sensitive << ( ap_CS_fsm_state108 );
    sensitive << ( StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_186_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    grp_pow_generic_double_s_fu_96_ap_start_reg = SC_LOGIC_0;
    grp_pow_generic_double_s_fu_125_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_modulus_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, fft_kernel_M_real_dout, "(port)fft_kernel_M_real_dout");
    sc_trace(mVcdFile, fft_kernel_M_real_empty_n, "(port)fft_kernel_M_real_empty_n");
    sc_trace(mVcdFile, fft_kernel_M_real_read, "(port)fft_kernel_M_real_read");
    sc_trace(mVcdFile, fft_kernel_M_imag_dout, "(port)fft_kernel_M_imag_dout");
    sc_trace(mVcdFile, fft_kernel_M_imag_empty_n, "(port)fft_kernel_M_imag_empty_n");
    sc_trace(mVcdFile, fft_kernel_M_imag_read, "(port)fft_kernel_M_imag_read");
    sc_trace(mVcdFile, fft_kernel_modu_M_r_din, "(port)fft_kernel_modu_M_r_din");
    sc_trace(mVcdFile, fft_kernel_modu_M_r_full_n, "(port)fft_kernel_modu_M_r_full_n");
    sc_trace(mVcdFile, fft_kernel_modu_M_r_write, "(port)fft_kernel_modu_M_r_write");
    sc_trace(mVcdFile, fft_kernel_modu_M_i_din, "(port)fft_kernel_modu_M_i_din");
    sc_trace(mVcdFile, fft_kernel_modu_M_i_full_n, "(port)fft_kernel_modu_M_i_full_n");
    sc_trace(mVcdFile, fft_kernel_modu_M_i_write, "(port)fft_kernel_modu_M_i_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, fft_kernel_M_real_blk_n, "fft_kernel_M_real_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond_fu_198_p2, "exitcond_fu_198_p2");
    sc_trace(mVcdFile, fft_kernel_M_imag_blk_n, "fft_kernel_M_imag_blk_n");
    sc_trace(mVcdFile, StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n, "StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n");
    sc_trace(mVcdFile, fft_kernel_modu_M_r_blk_n, "fft_kernel_modu_M_r_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state108, "ap_CS_fsm_state108");
    sc_trace(mVcdFile, StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n, "StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n");
    sc_trace(mVcdFile, fft_kernel_modu_M_i_blk_n, "fft_kernel_modu_M_i_blk_n");
    sc_trace(mVcdFile, r_2_fu_192_p2, "r_2_fu_192_p2");
    sc_trace(mVcdFile, r_2_reg_213, "r_2_reg_213");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, c_2_fu_204_p2, "c_2_fu_204_p2");
    sc_trace(mVcdFile, c_2_reg_221, "c_2_reg_221");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, fft_kernel_M_real_r_reg_226, "fft_kernel_M_real_r_reg_226");
    sc_trace(mVcdFile, fft_kernel_M_imag_r_reg_231, "fft_kernel_M_imag_r_reg_231");
    sc_trace(mVcdFile, x_assign_fu_171_p1, "x_assign_fu_171_p1");
    sc_trace(mVcdFile, x_assign_reg_236, "x_assign_reg_236");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, x_assign_1_fu_174_p1, "x_assign_1_fu_174_p1");
    sc_trace(mVcdFile, x_assign_1_reg_241, "x_assign_1_reg_241");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_96_ap_return, "grp_pow_generic_double_s_fu_96_ap_return");
    sc_trace(mVcdFile, tmp_i_reg_246, "tmp_i_reg_246");
    sc_trace(mVcdFile, ap_CS_fsm_state71, "ap_CS_fsm_state71");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_125_ap_return, "grp_pow_generic_double_s_fu_125_ap_return");
    sc_trace(mVcdFile, tmp_i1_reg_251, "tmp_i1_reg_251");
    sc_trace(mVcdFile, grp_fu_177_p2, "grp_fu_177_p2");
    sc_trace(mVcdFile, tmp_s_reg_256, "tmp_s_reg_256");
    sc_trace(mVcdFile, ap_CS_fsm_state76, "ap_CS_fsm_state76");
    sc_trace(mVcdFile, grp_fu_181_p2, "grp_fu_181_p2");
    sc_trace(mVcdFile, tmp_39_reg_261, "tmp_39_reg_261");
    sc_trace(mVcdFile, ap_CS_fsm_state107, "ap_CS_fsm_state107");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_96_ap_start, "grp_pow_generic_double_s_fu_96_ap_start");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_96_ap_done, "grp_pow_generic_double_s_fu_96_ap_done");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_96_ap_idle, "grp_pow_generic_double_s_fu_96_ap_idle");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_96_ap_ready, "grp_pow_generic_double_s_fu_96_ap_ready");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_125_ap_start, "grp_pow_generic_double_s_fu_125_ap_start");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_125_ap_done, "grp_pow_generic_double_s_fu_125_ap_done");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_125_ap_idle, "grp_pow_generic_double_s_fu_125_ap_idle");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_125_ap_ready, "grp_pow_generic_double_s_fu_125_ap_ready");
    sc_trace(mVcdFile, StgValue_299_real_r_fu_154_ap_start, "StgValue_299_real_r_fu_154_ap_start");
    sc_trace(mVcdFile, StgValue_299_real_r_fu_154_ap_done, "StgValue_299_real_r_fu_154_ap_done");
    sc_trace(mVcdFile, StgValue_299_real_r_fu_154_ap_idle, "StgValue_299_real_r_fu_154_ap_idle");
    sc_trace(mVcdFile, StgValue_299_real_r_fu_154_ap_ready, "StgValue_299_real_r_fu_154_ap_ready");
    sc_trace(mVcdFile, StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_din, "StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_din");
    sc_trace(mVcdFile, StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_write, "StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_write");
    sc_trace(mVcdFile, StgValue_300_imag_fu_161_ap_start, "StgValue_300_imag_fu_161_ap_start");
    sc_trace(mVcdFile, StgValue_300_imag_fu_161_ap_done, "StgValue_300_imag_fu_161_ap_done");
    sc_trace(mVcdFile, StgValue_300_imag_fu_161_ap_idle, "StgValue_300_imag_fu_161_ap_idle");
    sc_trace(mVcdFile, StgValue_300_imag_fu_161_ap_ready, "StgValue_300_imag_fu_161_ap_ready");
    sc_trace(mVcdFile, StgValue_300_imag_fu_161_fft_kernel_modu_M_i_din, "StgValue_300_imag_fu_161_fft_kernel_modu_M_i_din");
    sc_trace(mVcdFile, StgValue_300_imag_fu_161_fft_kernel_modu_M_i_write, "StgValue_300_imag_fu_161_fft_kernel_modu_M_i_write");
    sc_trace(mVcdFile, r_reg_74, "r_reg_74");
    sc_trace(mVcdFile, c_reg_85, "c_reg_85");
    sc_trace(mVcdFile, ap_block_state108, "ap_block_state108");
    sc_trace(mVcdFile, exitcond1_fu_186_p2, "exitcond1_fu_186_p2");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_96_ap_start_reg, "grp_pow_generic_double_s_fu_96_ap_start_reg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_NS_fsm_state5, "ap_NS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_pow_generic_double_s_fu_125_ap_start_reg, "grp_pow_generic_double_s_fu_125_ap_start_reg");
    sc_trace(mVcdFile, tmp_40_fu_167_p1, "tmp_40_fu_167_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state72, "ap_CS_fsm_state72");
    sc_trace(mVcdFile, ap_CS_fsm_state77, "ap_CS_fsm_state77");
#endif

    }
}

matrix_modulus::~matrix_modulus() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_pow_generic_double_s_fu_96;
    delete grp_pow_generic_double_s_fu_125;
    delete StgValue_299_real_r_fu_154;
    delete StgValue_300_imag_fu_161;
    delete WienerDeblur_fptreOg_U108;
    delete WienerDeblur_fpexKfY_U109;
    delete WienerDeblur_fpexKfY_U110;
    delete WienerDeblur_daddLf8_U111;
    delete WienerDeblur_dsqrMgi_U112;
}

void matrix_modulus::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void matrix_modulus::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_0;
}

void matrix_modulus::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_186_p2.read()))) {
        c_reg_85 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state108.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n.read())))) {
        c_reg_85 = c_2_reg_221.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pow_generic_double_s_fu_125_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_NS_fsm_state5.read()))) {
            grp_pow_generic_double_s_fu_125_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pow_generic_double_s_fu_125_ap_ready.read())) {
            grp_pow_generic_double_s_fu_125_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pow_generic_double_s_fu_96_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_NS_fsm_state5.read()))) {
            grp_pow_generic_double_s_fu_96_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pow_generic_double_s_fu_96_ap_ready.read())) {
            grp_pow_generic_double_s_fu_96_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !((esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_real_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_imag_empty_n.read()))) && 
         esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_1))) {
        r_reg_74 = r_2_reg_213.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_reg_74 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !((esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_real_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_imag_empty_n.read()))))) {
        c_2_reg_221 = c_2_fu_204_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_real_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_imag_empty_n.read()))))) {
        fft_kernel_M_imag_r_reg_231 = fft_kernel_M_imag_dout.read();
        fft_kernel_M_real_r_reg_226 = fft_kernel_M_real_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        r_2_reg_213 = r_2_fu_192_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state107.read())) {
        tmp_39_reg_261 = grp_fu_181_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state71.read())) {
        tmp_i1_reg_251 = grp_pow_generic_double_s_fu_125_ap_return.read();
        tmp_i_reg_246 = grp_pow_generic_double_s_fu_96_ap_return.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state76.read())) {
        tmp_s_reg_256 = grp_fu_177_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_assign_1_reg_241 = x_assign_1_fu_174_p1.read();
        x_assign_reg_236 = x_assign_fu_171_p1.read();
    }
}

void matrix_modulus::thread_StgValue_299_real_r_fu_154_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state108.read()) && 
         esl_seteq<1,1,1>(StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n.read(), ap_const_logic_1))) {
        StgValue_299_real_r_fu_154_ap_start = ap_const_logic_1;
    } else {
        StgValue_299_real_r_fu_154_ap_start = ap_const_logic_0;
    }
}

void matrix_modulus::thread_StgValue_300_imag_fu_161_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state108.read()) && 
         esl_seteq<1,1,1>(StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n.read(), ap_const_logic_1))) {
        StgValue_300_imag_fu_161_ap_start = ap_const_logic_1;
    } else {
        StgValue_300_imag_fu_161_ap_start = ap_const_logic_0;
    }
}

void matrix_modulus::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrix_modulus::thread_ap_CS_fsm_state107() {
    ap_CS_fsm_state107 = ap_CS_fsm.read()[106];
}

void matrix_modulus::thread_ap_CS_fsm_state108() {
    ap_CS_fsm_state108 = ap_CS_fsm.read()[107];
}

void matrix_modulus::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void matrix_modulus::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void matrix_modulus::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void matrix_modulus::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void matrix_modulus::thread_ap_CS_fsm_state71() {
    ap_CS_fsm_state71 = ap_CS_fsm.read()[70];
}

void matrix_modulus::thread_ap_CS_fsm_state72() {
    ap_CS_fsm_state72 = ap_CS_fsm.read()[71];
}

void matrix_modulus::thread_ap_CS_fsm_state76() {
    ap_CS_fsm_state76 = ap_CS_fsm.read()[75];
}

void matrix_modulus::thread_ap_CS_fsm_state77() {
    ap_CS_fsm_state77 = ap_CS_fsm.read()[76];
}

void matrix_modulus::thread_ap_NS_fsm_state5() {
    ap_NS_fsm_state5 = ap_NS_fsm.read()[4];
}

void matrix_modulus::thread_ap_block_state108() {
    ap_block_state108 = (esl_seteq<1,1,1>(ap_const_logic_0, StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n.read()));
}

void matrix_modulus::thread_ap_block_state3() {
    ap_block_state3 = ((esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_real_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_imag_empty_n.read())));
}

void matrix_modulus::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_186_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_modulus::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_modulus::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_186_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_modulus::thread_c_2_fu_204_p2() {
    c_2_fu_204_p2 = (!c_reg_85.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(c_reg_85.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void matrix_modulus::thread_exitcond1_fu_186_p2() {
    exitcond1_fu_186_p2 = (!r_reg_74.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(r_reg_74.read() == ap_const_lv9_100);
}

void matrix_modulus::thread_exitcond_fu_198_p2() {
    exitcond_fu_198_p2 = (!c_reg_85.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(c_reg_85.read() == ap_const_lv9_100);
}

void matrix_modulus::thread_fft_kernel_M_imag_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0))) {
        fft_kernel_M_imag_blk_n = fft_kernel_M_imag_empty_n.read();
    } else {
        fft_kernel_M_imag_blk_n = ap_const_logic_1;
    }
}

void matrix_modulus::thread_fft_kernel_M_imag_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_real_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_imag_empty_n.read()))))) {
        fft_kernel_M_imag_read = ap_const_logic_1;
    } else {
        fft_kernel_M_imag_read = ap_const_logic_0;
    }
}

void matrix_modulus::thread_fft_kernel_M_real_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0))) {
        fft_kernel_M_real_blk_n = fft_kernel_M_real_empty_n.read();
    } else {
        fft_kernel_M_real_blk_n = ap_const_logic_1;
    }
}

void matrix_modulus::thread_fft_kernel_M_real_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_real_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_imag_empty_n.read()))))) {
        fft_kernel_M_real_read = ap_const_logic_1;
    } else {
        fft_kernel_M_real_read = ap_const_logic_0;
    }
}

void matrix_modulus::thread_fft_kernel_modu_M_i_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state108.read())) {
        fft_kernel_modu_M_i_blk_n = StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n.read();
    } else {
        fft_kernel_modu_M_i_blk_n = ap_const_logic_1;
    }
}

void matrix_modulus::thread_fft_kernel_modu_M_i_din() {
    fft_kernel_modu_M_i_din = StgValue_300_imag_fu_161_fft_kernel_modu_M_i_din.read();
}

void matrix_modulus::thread_fft_kernel_modu_M_i_write() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state108.read())) {
        fft_kernel_modu_M_i_write = StgValue_300_imag_fu_161_fft_kernel_modu_M_i_write.read();
    } else {
        fft_kernel_modu_M_i_write = ap_const_logic_0;
    }
}

void matrix_modulus::thread_fft_kernel_modu_M_r_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state108.read())) {
        fft_kernel_modu_M_r_blk_n = StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n.read();
    } else {
        fft_kernel_modu_M_r_blk_n = ap_const_logic_1;
    }
}

void matrix_modulus::thread_fft_kernel_modu_M_r_din() {
    fft_kernel_modu_M_r_din = StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_din.read();
}

void matrix_modulus::thread_fft_kernel_modu_M_r_write() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state108.read())) {
        fft_kernel_modu_M_r_write = StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_write.read();
    } else {
        fft_kernel_modu_M_r_write = ap_const_logic_0;
    }
}

void matrix_modulus::thread_grp_pow_generic_double_s_fu_125_ap_start() {
    grp_pow_generic_double_s_fu_125_ap_start = grp_pow_generic_double_s_fu_125_ap_start_reg.read();
}

void matrix_modulus::thread_grp_pow_generic_double_s_fu_96_ap_start() {
    grp_pow_generic_double_s_fu_96_ap_start = grp_pow_generic_double_s_fu_96_ap_start_reg.read();
}

void matrix_modulus::thread_r_2_fu_192_p2() {
    r_2_fu_192_p2 = (!r_reg_74.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(r_reg_74.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void matrix_modulus::thread_ap_NS_fsm() {
    if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state1))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else {
            ap_NS_fsm = ap_ST_fsm_state1;
        }
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state2))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_186_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state1;
        } else {
            ap_NS_fsm = ap_ST_fsm_state3;
        }
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state3))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !((esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_real_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_imag_empty_n.read()))) && esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_1))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_real_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_fu_198_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, fft_kernel_M_imag_empty_n.read()))))) {
            ap_NS_fsm = ap_ST_fsm_state4;
        } else {
            ap_NS_fsm = ap_ST_fsm_state3;
        }
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state4))
    {
        ap_NS_fsm = ap_ST_fsm_state5;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state5))
    {
        ap_NS_fsm = ap_ST_fsm_state6;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state6))
    {
        ap_NS_fsm = ap_ST_fsm_state7;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state7))
    {
        ap_NS_fsm = ap_ST_fsm_state8;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state8))
    {
        ap_NS_fsm = ap_ST_fsm_state9;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state9))
    {
        ap_NS_fsm = ap_ST_fsm_state10;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state10))
    {
        ap_NS_fsm = ap_ST_fsm_state11;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state11))
    {
        ap_NS_fsm = ap_ST_fsm_state12;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state12))
    {
        ap_NS_fsm = ap_ST_fsm_state13;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state13))
    {
        ap_NS_fsm = ap_ST_fsm_state14;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state14))
    {
        ap_NS_fsm = ap_ST_fsm_state15;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state15))
    {
        ap_NS_fsm = ap_ST_fsm_state16;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state16))
    {
        ap_NS_fsm = ap_ST_fsm_state17;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state17))
    {
        ap_NS_fsm = ap_ST_fsm_state18;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state18))
    {
        ap_NS_fsm = ap_ST_fsm_state19;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state19))
    {
        ap_NS_fsm = ap_ST_fsm_state20;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state20))
    {
        ap_NS_fsm = ap_ST_fsm_state21;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state21))
    {
        ap_NS_fsm = ap_ST_fsm_state22;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state22))
    {
        ap_NS_fsm = ap_ST_fsm_state23;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state23))
    {
        ap_NS_fsm = ap_ST_fsm_state24;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state24))
    {
        ap_NS_fsm = ap_ST_fsm_state25;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state25))
    {
        ap_NS_fsm = ap_ST_fsm_state26;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state26))
    {
        ap_NS_fsm = ap_ST_fsm_state27;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state27))
    {
        ap_NS_fsm = ap_ST_fsm_state28;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state28))
    {
        ap_NS_fsm = ap_ST_fsm_state29;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state29))
    {
        ap_NS_fsm = ap_ST_fsm_state30;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state30))
    {
        ap_NS_fsm = ap_ST_fsm_state31;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state31))
    {
        ap_NS_fsm = ap_ST_fsm_state32;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state32))
    {
        ap_NS_fsm = ap_ST_fsm_state33;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state33))
    {
        ap_NS_fsm = ap_ST_fsm_state34;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state34))
    {
        ap_NS_fsm = ap_ST_fsm_state35;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state35))
    {
        ap_NS_fsm = ap_ST_fsm_state36;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state36))
    {
        ap_NS_fsm = ap_ST_fsm_state37;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state37))
    {
        ap_NS_fsm = ap_ST_fsm_state38;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state38))
    {
        ap_NS_fsm = ap_ST_fsm_state39;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state39))
    {
        ap_NS_fsm = ap_ST_fsm_state40;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state40))
    {
        ap_NS_fsm = ap_ST_fsm_state41;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state41))
    {
        ap_NS_fsm = ap_ST_fsm_state42;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state42))
    {
        ap_NS_fsm = ap_ST_fsm_state43;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state43))
    {
        ap_NS_fsm = ap_ST_fsm_state44;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state44))
    {
        ap_NS_fsm = ap_ST_fsm_state45;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state45))
    {
        ap_NS_fsm = ap_ST_fsm_state46;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state46))
    {
        ap_NS_fsm = ap_ST_fsm_state47;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state47))
    {
        ap_NS_fsm = ap_ST_fsm_state48;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state48))
    {
        ap_NS_fsm = ap_ST_fsm_state49;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state49))
    {
        ap_NS_fsm = ap_ST_fsm_state50;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state50))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state51))
    {
        ap_NS_fsm = ap_ST_fsm_state52;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state52))
    {
        ap_NS_fsm = ap_ST_fsm_state53;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state53))
    {
        ap_NS_fsm = ap_ST_fsm_state54;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state54))
    {
        ap_NS_fsm = ap_ST_fsm_state55;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state55))
    {
        ap_NS_fsm = ap_ST_fsm_state56;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state56))
    {
        ap_NS_fsm = ap_ST_fsm_state57;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state57))
    {
        ap_NS_fsm = ap_ST_fsm_state58;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state58))
    {
        ap_NS_fsm = ap_ST_fsm_state59;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state59))
    {
        ap_NS_fsm = ap_ST_fsm_state60;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state60))
    {
        ap_NS_fsm = ap_ST_fsm_state61;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state61))
    {
        ap_NS_fsm = ap_ST_fsm_state62;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state62))
    {
        ap_NS_fsm = ap_ST_fsm_state63;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state63))
    {
        ap_NS_fsm = ap_ST_fsm_state64;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state64))
    {
        ap_NS_fsm = ap_ST_fsm_state65;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state65))
    {
        ap_NS_fsm = ap_ST_fsm_state66;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state66))
    {
        ap_NS_fsm = ap_ST_fsm_state67;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state67))
    {
        ap_NS_fsm = ap_ST_fsm_state68;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state68))
    {
        ap_NS_fsm = ap_ST_fsm_state69;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state69))
    {
        ap_NS_fsm = ap_ST_fsm_state70;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state70))
    {
        ap_NS_fsm = ap_ST_fsm_state71;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state71))
    {
        ap_NS_fsm = ap_ST_fsm_state72;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state72))
    {
        ap_NS_fsm = ap_ST_fsm_state73;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state73))
    {
        ap_NS_fsm = ap_ST_fsm_state74;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state74))
    {
        ap_NS_fsm = ap_ST_fsm_state75;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state75))
    {
        ap_NS_fsm = ap_ST_fsm_state76;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state76))
    {
        ap_NS_fsm = ap_ST_fsm_state77;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state77))
    {
        ap_NS_fsm = ap_ST_fsm_state78;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state78))
    {
        ap_NS_fsm = ap_ST_fsm_state79;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state79))
    {
        ap_NS_fsm = ap_ST_fsm_state80;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state80))
    {
        ap_NS_fsm = ap_ST_fsm_state81;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state81))
    {
        ap_NS_fsm = ap_ST_fsm_state82;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state82))
    {
        ap_NS_fsm = ap_ST_fsm_state83;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state83))
    {
        ap_NS_fsm = ap_ST_fsm_state84;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state84))
    {
        ap_NS_fsm = ap_ST_fsm_state85;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state85))
    {
        ap_NS_fsm = ap_ST_fsm_state86;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state86))
    {
        ap_NS_fsm = ap_ST_fsm_state87;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state87))
    {
        ap_NS_fsm = ap_ST_fsm_state88;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state88))
    {
        ap_NS_fsm = ap_ST_fsm_state89;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state89))
    {
        ap_NS_fsm = ap_ST_fsm_state90;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state90))
    {
        ap_NS_fsm = ap_ST_fsm_state91;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state91))
    {
        ap_NS_fsm = ap_ST_fsm_state92;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state92))
    {
        ap_NS_fsm = ap_ST_fsm_state93;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state93))
    {
        ap_NS_fsm = ap_ST_fsm_state94;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state94))
    {
        ap_NS_fsm = ap_ST_fsm_state95;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state95))
    {
        ap_NS_fsm = ap_ST_fsm_state96;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state96))
    {
        ap_NS_fsm = ap_ST_fsm_state97;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state97))
    {
        ap_NS_fsm = ap_ST_fsm_state98;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state98))
    {
        ap_NS_fsm = ap_ST_fsm_state99;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state99))
    {
        ap_NS_fsm = ap_ST_fsm_state100;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state100))
    {
        ap_NS_fsm = ap_ST_fsm_state101;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state101))
    {
        ap_NS_fsm = ap_ST_fsm_state102;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state102))
    {
        ap_NS_fsm = ap_ST_fsm_state103;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state103))
    {
        ap_NS_fsm = ap_ST_fsm_state104;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state104))
    {
        ap_NS_fsm = ap_ST_fsm_state105;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state105))
    {
        ap_NS_fsm = ap_ST_fsm_state106;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state106))
    {
        ap_NS_fsm = ap_ST_fsm_state107;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state107))
    {
        ap_NS_fsm = ap_ST_fsm_state108;
    }
    else if (esl_seteq<1,108,108>(ap_CS_fsm.read(), ap_ST_fsm_state108))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state108.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, StgValue_299_real_r_fu_154_fft_kernel_modu_M_r_blk_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, StgValue_300_imag_fu_161_fft_kernel_modu_M_i_blk_n.read())))) {
            ap_NS_fsm = ap_ST_fsm_state3;
        } else {
            ap_NS_fsm = ap_ST_fsm_state108;
        }
    }
    else
    {
        ap_NS_fsm =  (sc_lv<108>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
}

