// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _operator_mul_float_HH_
#define _operator_mul_float_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "operator_mul_assign_float.h"

namespace ap_rtl {

struct operator_mul_float : public sc_module {
    // Port declarations 25
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > gauss_blur_M_real_dout;
    sc_in< sc_logic > gauss_blur_M_real_empty_n;
    sc_out< sc_logic > gauss_blur_M_real_read;
    sc_in< sc_lv<32> > gauss_blur_M_imag_dout;
    sc_in< sc_logic > gauss_blur_M_imag_empty_n;
    sc_out< sc_logic > gauss_blur_M_imag_read;
    sc_in< sc_logic > ap_ce;
    sc_in< sc_lv<32> > G_M_real_dout;
    sc_in< sc_logic > G_M_real_empty_n;
    sc_out< sc_logic > G_M_real_read;
    sc_in< sc_lv<32> > G_M_imag_dout;
    sc_in< sc_logic > G_M_imag_empty_n;
    sc_out< sc_logic > G_M_imag_read;
    sc_out< sc_lv<32> > ap_return_0;
    sc_out< sc_lv<32> > ap_return_1;
    sc_out< sc_logic > gauss_blur_M_real_blk_n;
    sc_out< sc_logic > gauss_blur_M_imag_blk_n;
    sc_out< sc_logic > G_M_real_blk_n;
    sc_out< sc_logic > G_M_imag_blk_n;


    // Module declarations
    operator_mul_float(sc_module_name name);
    SC_HAS_PROCESS(operator_mul_float);

    ~operator_mul_float();

    sc_trace_file* mVcdFile;

    operator_mul_assign_float* grp_operator_mul_assign_float_fu_34;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter5;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter6;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter7;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter8;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter9;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > grp_operator_mul_assign_float_fu_34_p_z_M_real_blk_n;
    sc_signal< sc_logic > grp_operator_mul_assign_float_fu_34_p_z_M_imag_blk_n;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter6;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter7;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter8;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter9;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > grp_operator_mul_assign_float_fu_34_ap_start;
    sc_signal< sc_logic > grp_operator_mul_assign_float_fu_34_ap_done;
    sc_signal< sc_logic > grp_operator_mul_assign_float_fu_34_ap_idle;
    sc_signal< sc_logic > grp_operator_mul_assign_float_fu_34_ap_ready;
    sc_signal< sc_logic > grp_operator_mul_assign_float_fu_34_p_z_M_real_read;
    sc_signal< sc_logic > grp_operator_mul_assign_float_fu_34_p_z_M_imag_read;
    sc_signal< sc_logic > grp_operator_mul_assign_float_fu_34_ap_ce;
    sc_signal< sc_lv<32> > grp_operator_mul_assign_float_fu_34_ap_return_0;
    sc_signal< sc_lv<32> > grp_operator_mul_assign_float_fu_34_ap_return_1;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0_ignore_call4;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1_ignore_call4;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2_ignore_call4;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3_ignore_call4;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4_ignore_call4;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5_ignore_call4;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter6_ignore_call4;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter7_ignore_call4;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter8_ignore_call4;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter9_ignore_call4;
    sc_signal< bool > ap_block_pp0_stage0_11001_ignoreCallOp13;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0_0to8;
    sc_signal< sc_logic > ap_reset_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_pp0_stage0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_G_M_imag_blk_n();
    void thread_G_M_imag_read();
    void thread_G_M_real_blk_n();
    void thread_G_M_real_read();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_11001_ignoreCallOp13();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state10_pp0_stage0_iter9();
    void thread_ap_block_state10_pp0_stage0_iter9_ignore_call4();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state1_pp0_stage0_iter0_ignore_call4();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state2_pp0_stage0_iter1_ignore_call4();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state3_pp0_stage0_iter2_ignore_call4();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_ap_block_state4_pp0_stage0_iter3_ignore_call4();
    void thread_ap_block_state5_pp0_stage0_iter4();
    void thread_ap_block_state5_pp0_stage0_iter4_ignore_call4();
    void thread_ap_block_state6_pp0_stage0_iter5();
    void thread_ap_block_state6_pp0_stage0_iter5_ignore_call4();
    void thread_ap_block_state7_pp0_stage0_iter6();
    void thread_ap_block_state7_pp0_stage0_iter6_ignore_call4();
    void thread_ap_block_state8_pp0_stage0_iter7();
    void thread_ap_block_state8_pp0_stage0_iter7_ignore_call4();
    void thread_ap_block_state9_pp0_stage0_iter8();
    void thread_ap_block_state9_pp0_stage0_iter8_ignore_call4();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_enable_reg_pp0_iter0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_idle_pp0_0to8();
    void thread_ap_ready();
    void thread_ap_reset_idle_pp0();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_gauss_blur_M_imag_blk_n();
    void thread_gauss_blur_M_imag_read();
    void thread_gauss_blur_M_real_blk_n();
    void thread_gauss_blur_M_real_read();
    void thread_grp_operator_mul_assign_float_fu_34_ap_ce();
    void thread_grp_operator_mul_assign_float_fu_34_ap_start();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
