// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _real_r_HH_
#define _real_r_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct real_r : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > p_val;
    sc_out< sc_lv<32> > fft_kernel_modu_M_r_din;
    sc_in< sc_logic > fft_kernel_modu_M_r_full_n;
    sc_out< sc_logic > fft_kernel_modu_M_r_write;
    sc_out< sc_logic > fft_kernel_modu_M_r_blk_n;


    // Module declarations
    real_r(sc_module_name name);
    SC_HAS_PROCESS(real_r);

    ~real_r();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_fft_kernel_modu_M_r_blk_n();
    void thread_fft_kernel_modu_M_r_din();
    void thread_fft_kernel_modu_M_r_write();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
